import jsPDF from "jspdf";

export function generatePDF(result) {
    const doc = new jsPDF();

    let y = 20;

    doc.setFontSize(22);
    doc.text("AI Resume Analysis Report", 20, y);

    y += 15;

    doc.setFontSize(16);
    doc.text(`ATS Score: ${result.atsScore}/100`, 20, y);

    y += 15;

    doc.setFontSize(18);
    doc.text("Summary", 20, y);

    y += 10;

    doc.setFontSize(12);
    const summary = doc.splitTextToSize(result.summary, 170);
    doc.text(summary, 20, y);

    y += summary.length * 7 + 10;

    doc.setFontSize(18);
    doc.text("Strengths", 20, y);

    y += 10;

    result.strengths.forEach((item) => {
        doc.text(`• ${item}`, 25, y);
        y += 8;
    });

    y += 5;

    doc.setFontSize(18);
    doc.text("Missing Skills", 20, y);

    y += 10;

    result.missingSkills.forEach((item) => {
        doc.text(`• ${item}`, 25, y);
        y += 8;
    });

    y += 5;

    doc.setFontSize(18);
    doc.text("Interview Questions", 20, y);

    y += 10;

    result.interviewQuestions.forEach((item, index) => {
        const question = doc.splitTextToSize(
            `${index + 1}. ${item}`,
            170
        );

        doc.text(question, 20, y);

        y += question.length * 7;
    });

    y += 15;

    doc.setFontSize(11);

    doc.text(
        `Generated on: ${new Date().toLocaleString()}`,
        20,
        y
    );

    y += 8;

    doc.text("Generated by AI Resume Analyzer", 20, y);

    doc.save("AI_Resume_Report.pdf");
}